export const SET_BOARD = 'SET_BOARD'
export const SET_STEPS = 'SET_STEPS'
export const RESET_BOARD = 'RESET_BOARD'
export const ADD_CHESSMAN = 'ADD_CHESSMAN'
export const BACKWARD = 'BACKWARD'
export const FORWARD = 'FORWARD'
export const SET_FIVES = 'SET_FIVES'
export const SET_SPREAD = 'SET_SPREAD'